services:
  postgres:
    image: postgres:15
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.production
      # Optionally, uncomment if you need to enforce production mode:
      # NODE_ENV: production
    # For development convenience, you might add a volume mount:
    # volumes:
    #   - ./server/src:/app/src
    #   - /app/node_modules

volumes:
  pgdata:
