services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server   # Mounts the entire project directory into /app
      # Optionally, if you want to avoid overwriting node_modules installed in the container:
      # - /app/node_modules
    env_file:
      - .env.development
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: